### ISSUE TITLE
python2.7环境下中文微信昵称或者群组报编码错误

### ISSUE THREAD

**Issue by lyp2008001** [bluedazzle/wechat_sender#10]
group = bot.groups().search('游否')[0]
  File "C:\Python27\lib\site-packages\wxpy\api\chats\groups.py", line 71, in search
    return Groups(filter(match, self))
  File "C:\Python27\lib\site-packages\wxpy\api\chats\groups.py", line 61, in match
    if not match_name(group, keywords):
  File "C:\Python27\lib\site-packages\wxpy\utils\misc.py", line 185, in match_name
    if kw in str(getattr(chat, attr, '')).lower():
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe6 in position 0: unexpected end of data

**Comment by bluedazzle** [comment]
方便提供下操作系统版本嘛？
@lyp2008001

**Comment by lyp2008001** [comment]
@bluedazzle win10企业版

**Comment by leemon9527** [comment]
请问问题解决了吗。好像也碰到了这个问题

**Comment by bluedazzle** [comment]
看起来是 wxpy Windows 下编码的问题，会尽快修复。到时候可能需要重新安装 wxpy 库

**Comment by leemon9527** [comment]
刚才研究了下
misc.py 中引入了future.builtins的str
    if PY2:
        from future.builtins import str
方法prepare_keywords中的参数如果使用python2.7的默认的str会导致判断isinstance(keyword,str)不成立

导致最后返回的map结果出错。

我暂时的解决办法是
在微信发送端的脚本中同样引入     from future.builtins import str ,然后在search的时候强制下类型转换
示例

from wxpy.compatible import PY2
if PY2:
    from future.builtins import str
    
def main():
    bot = Bot()

    my = bot.friends().search(str('蓦然'))
    listen(bot,receivers=my)

**Comment by bluedazzle** [comment]
嗯嗯，Windows 下系统编码不是 utf-8 所以 future.builtins 的 str 会出错。你可以先那样解决，我在 wxpy develop 分支修复了这个问题。你可以安装这个分支的 wxpy 试试 @leemon9527

**Comment by leemon9527** [comment]
@bluedazzle 刚才重新安装了wxpy的develop分支，好像还会报错
  File "D:/Seafile/pyproject/PycharmTestProjects/wechat_msg_test/wx_msg.py", line 19, in <module>
    main()
  File "D:/Seafile/pyproject/PycharmTestProjects/wechat_msg_test/wx_msg.py", line 14, in main
    my = bot.friends().search('蓦然')
  File "C:\Python27_10\lib\site-packages\wxpy-0.3.9.7-py2.7.egg\wxpy\api\chats\chats.py", line 50, in search
    return Chats(filter(match, self), self.source)
  File "C:\Python27_10\lib\site-packages\wxpy-0.3.9.7-py2.7.egg\wxpy\api\chats\chats.py", line 44, in match
    if not match_name(chat, keywords):
  File "C:\Python27_10\lib\site-packages\wxpy-0.3.9.7-py2.7.egg\wxpy\utils\misc.py", line 187, in match_name
    if kw in '{0}'.format(getattr(chat, attr, '')).lower():
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 0: unexpected end of data

**Comment by bluedazzle** [comment]
ok，我再看看

**Comment by babizhu** [comment]
linux下面也有这个问题，4.4.0-79-generic #100-Ubuntu 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)

**Comment by slyang-git** [comment]
group = bot.groups().search(u'游否')[0]

'游否' 前面 加一个 u --> u'游否'

解决了

**Comment by JustDoItQz** [comment]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/developer/python_workplace/Python/wechat_sender_out.py", line 1, in <module>
    from wechat_sender import Sender
  File "C:\developer\python_workplace\Python\wechat_sender.py", line 4, in <module>
    listen(bot)
NameError: name 'listen' is not defined

**Comment by JustDoItQz** [comment]
@bluedazzle  该怎么解决？

**Comment by JustDoItQz** [comment]
我下载的最新版

**Comment by bluedazzle** [comment]
@JustDoItQz 不要把你的文件名命名为 wechat_sender.py 换个名字
