### ISSUE TITLE
使用host一直连接失败

### ISSUE THREAD

**Issue by xingsu1021** [bluedazzle/wechat_sender#11]
[root@10-8-6-109 ~]# /usr/local/python3/bin/python3 t2.py 
Traceback (most recent call last):
  File "t2.py", line 9, in <module>
    sender.send("hello")
  File "/usr/local/python3/lib/python3.6/site-packages/wechat_sender/sender.py", line 70, in send
    res = requests.post(url, data=data, timeout=self.timeout)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/sessions.py", line 617, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/python3/lib/python3.6/site-packages/requests/sessions.py", line 708, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '10.8.6.109:19090/message'

linux和windows都试过，python版本3.6，但是浏览器是可以访问的，求教

**Comment by xingsu1021** [comment]
host例子不对，问题解决了
