### ISSUE TITLE
每隔一段时间机器人就会自动退出，查看console日志如下

### ISSUE THREAD

**Issue by leemon9527** [bluedazzle/wechat_sender#12]
`ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fc857b51838>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 1026, in _run
    return self.callback()
  File "/usr/local/lib/python2.7/site-packages/wechat_sender/listener.py", line 238, in check_bot
    glb.wxbot.send_msg(message)
  File "/usr/local/lib/python2.7/site-packages/wechat_sender/objects.py", line 57, in send_msg
    current_receiver.send_msg(msg)
  File "/usr/local/lib/python2.7/site-packages/wxpy/api/chats/chat.py", line 54, in wrapped
    ret = do_send()
  File "/usr/local/lib/python2.7/site-packages/wxpy/utils/misc.py", line 71, in wrapped
    smart_map(check_response_body, ret)
  File "/usr/local/lib/python2.7/site-packages/wxpy/utils/misc.py", line 205, in smart_map
    return func(i, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/wxpy/utils/misc.py", line 52, in check_response_body
    raise ResponseError(err_code=err_code, err_msg=err_msg)
ResponseError: err_code: 3; err_msg:
LOG OUT!
INFO:itchat:LOG OUT!
`
这个有办法解决吗，用的小号登录的，使用安卓 的双开软件。

**Comment by thewenzhi** [comment]
您好,我也遇到相同的问题,请问解决了嘛?
