### ISSUE TITLE
运行wechat_sender报错

### ISSUE THREAD

**Issue by Hello-Linux** [bluedazzle/wechat_sender#15]
python wechat_sender.py 
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "wechat_sender.py", line 2, in <module>
    from wechat_sender import *
  File "/root/wechat_sender.py", line 3, in <module>
    bot = Bot()
  File "/usr/lib/python2.7/site-packages/wxpy/api/bot.py", line 88, in __init__
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined

**Comment by Big2Cat** [comment]
bot=Bot(console_qr=True)
